version: "2"
services:

  app:
    container_name: authentication_app
    restart: always
    build: .
    ports:
      - "8000:8000"


  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"